#!/usr/bin/env python3
"""Author structured A2-listening exam data → output/<id>/exam.json.

Why this exists: the raw transcript replays each video clip once per question,
so the same dialogue appears 3x. This script reorganises every video into
SCENARIOS (dialogue listed once) + QUESTIONS (each with answer, complete
source citation, reasoning, and trap note). Dialogue text+translation is
pulled from data.json segments; everything else is hand-authored here.

The exam.json it writes is the data layer for both the PDF handout
(make_pdfs.py) and the future clickable-audio website.

Usage: python3 make_exam.py            # build all videos defined below
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / 'output'


def ts(sec: float) -> str:
    return f"{int(sec // 60)}:{int(sec % 60):02d}"


def pull_dialogue(segs, a: int, b: int):
    """Pull segments [a, b] inclusive → list of {t, nl, zh}."""
    out = []
    for i in range(a, b + 1):
        s = segs[i]
        nl = (s.get('text') or '').strip()
        if not nl:
            continue
        out.append({
            't': ts(s.get('start', 0)),
            'nl': nl,
            'zh': (s.get('translation') or '').strip(),
        })
    return out


# ─────────────────────────────────────────────────────────────────────
# PART 1 — EXAMEN A2 luisteren 2026 inburgering PART 1  (_iC1Pooi2UA)
# ─────────────────────────────────────────────────────────────────────
PART1 = {
    'video_id': '_iC1Pooi2UA',
    'exam_type': 'A2 Luisteren · Inburgering',
    'intro': (
        'A2 聽力考試的固定節奏：先讀題目 → 看一次影片 → 作答。每換一題，'
        '同一段影片就會「重新播放一次」。這份講義把重播折疊掉——每個場景的'
        '對話只列一次，後面接該場景的所有考題，每題都標出答案藏在原文哪一句。'
    ),
    'scenarios': [
        {
            'title_zh': '在路上遇到老朋友', 'title_nl': 'Steven komt Yari tegen op straat',
            'kind': '對話', 'dialogue': (2, 11),
            'context_zh': 'Steven 在路上遇到 Yari，兩人停下來聊天。Steven 報喜並邀請 Yari。',
            'vocab': [
                {'nl': 'zwanger', 'zh': '懷孕的'},
                {'nl': 'uitnodigen', 'zh': '邀請'},
                {'nl': 'klussen', 'zh': '做修繕／裝修的雜工'},
                {'nl': 'een muur schilderen', 'zh': '粉刷牆壁'},
                {'nl': 'hartstikke gezellig', 'zh': '非常溫馨愉快（口語）'},
            ],
            'patterns': [
                {'nl': 'Hoe lang is ... al ...?', 'zh': '……已經……多久了？',
                 'note': '問某狀態持續多久，al 強調「已經」。'},
                {'nl': 'Ik wilde je uitnodigen om ... te ...', 'zh': '我想邀請你來……',
                 'note': 'om + te + 原形動詞，表「目的」。'},
            ],
            'questions': [
                {'n': 1, 't': '1:17',
                 'q_nl': 'Hoe lang is Daniëlle zwanger?',
                 'q_zh': 'Daniëlle 懷孕幾個月了？',
                 'options': [('Twee maanden', '兩個月'), ('Drie maanden', '三個月'),
                             ('Vier maanden', '四個月')],
                 'answer': 1,
                 'source': [('0:38', 'Hoe lang is Daniëlle al zwanger?', '（Steven 問）她懷孕多久了？'),
                            ('0:43', 'Drie maanden.', '三個月。')],
                 'explain': 'Steven 問「Hoe lang is Daniëlle al zwanger?」，Yari 緊接著回答「Drie maanden」。聽到問句馬上抓住下一句的數字就是答案。',
                 'trap': '前面 Steven 說「komende zaterdag」「一起慶祝」，數字訊息密集，別把週六、第一胎這些細節跟月份搞混。'},
                {'n': 2, 't': '2:41',
                 'q_nl': 'Wanneer komt Yari eten bij Steven en Daniëlle?',
                 'q_zh': 'Yari 哪一天要去 Steven 和 Daniëlle 家吃飯？',
                 'options': [('Woensdag', '星期三'), ('Zaterdag', '星期六'), ('Zondag', '星期日')],
                 'answer': 1,
                 'source': [('0:47', 'daarom wilde ik je uitnodigen om komende zaterdag bij ons te komen eten',
                             '所以我想邀你這個星期六來我們家吃飯')],
                 'explain': 'Steven 直接說「komende zaterdag ... te komen eten」——下個星期六來吃飯。komende = 即將到來的。',
                 'trap': '選項只有三個星期幾，原文只出現一個（zaterdag），其餘是干擾。'},
                {'n': 3, 't': '4:00',
                 'q_nl': 'Wat vraagt Steven aan Yari?',
                 'q_zh': 'Steven 拜託 Yari 幫什麼忙？',
                 'options': [('Of hij wil komen klussen', '能不能來幫忙裝修'),
                             ('Of hij een kinderbedje wil maken', '能不能做一張嬰兒床'),
                             ('Of hij wil helpen bij het koken', '能不能幫忙煮飯')],
                 'answer': 0,
                 'source': [('1:00', 'Zeg, kan jij helpen klussen de aankomende tijd?',
                             '欸，你最近能來幫忙裝修嗎？'),
                            ('1:00', 'Er moeten een aantal muren geschilderd worden.',
                             '有幾面牆要粉刷。')],
                 'explain': 'Steven 問「kan jij helpen klussen」，並補充要粉刷牆、鋪新地板——都是 klussen（裝修雜工）的內容。',
                 'trap': '嬰兒床、煮飯 原文完全沒提到，是憑「家裡有小孩、要慶祝」聯想出來的陷阱。'},
            ],
        },
        {
            'title_zh': '堅果公司的徵人廣告', 'title_nl': 'Hassan kijkt naar een filmpje van een bedrijf',
            'kind': '廣告影片', 'dialogue': (47, 56),
            'context_zh': 'Hassan 在網路上看到一支公司的影片，是一家堅果公司的徵才廣告。',
            'vocab': [
                {'nl': 'noten / notjes', 'zh': '堅果（notjes 為暱稱小詞）'},
                {'nl': 'verwerken en verpakken', 'zh': '加工與包裝'},
                {'nl': 'de fabriek', 'zh': '工廠'},
                {'nl': 'het magazijn', 'zh': '倉庫'},
                {'nl': 'de chauffeur', 'zh': '司機'},
            ],
            'patterns': [
                {'nl': 'Die ... komen uit ...', 'zh': '那些……來自……',
                 'note': '說明來源／產地。'},
                {'nl': 'Wij zoeken ... mensen voor ...', 'zh': '我們在找……人來做……',
                 'note': '徵才常用句。'},
            ],
            'questions': [
                {'n': 4, 't': '5:47',
                 'q_nl': 'Waarom noemt de man Zuid-Amerika, Azië en Afrika?',
                 'q_zh': '影片裡的人為什麼提到南美洲、亞洲和非洲？',
                 'options': [('Daar staan de fabrieken van het bedrijf', '公司的工廠在那些地方'),
                             ('Daar worden de snacks van het bedrijf verkocht', '公司的零食賣到那些地方'),
                             ('Daar groeien de notjes die het bedrijf gebruikt', '公司用的堅果產自那些地方')],
                 'answer': 2,
                 'source': [('5:03', 'Die noten komen uit veel verschillende landen over de hele wereld.',
                             '那些堅果來自世界各地許多不同的國家。'),
                            ('5:08', 'Zuid-Amerika. Azië. Afrika.', '南美洲、亞洲、非洲。')],
                 'explain': '三個洲名緊接在「堅果來自世界各地」之後——這三個地名就是在舉例「產地」。',
                 'trap': '原文明說「In Nederland verwerken en verpakken we de notjes」——工廠在荷蘭；之後送到超市，不是賣到那三洲。'},
            ],
        },
        {
            'title_zh': '語言課程的廣播通知', 'title_nl': 'Julio hoort een omroepbericht over cursussen',
            'kind': '廣播通知', 'dialogue': (77, 83),
            'context_zh': 'Julio 在上荷蘭語課程，他聽到一則關於新課程的廣播通知。他想上 Nederlands 3。',
            'vocab': [
                {'nl': 'het omroepbericht', 'zh': '廣播通知'},
                {'nl': 'zit bijna vol', 'zh': '快額滿了'},
                {'nl': 'de plaats', 'zh': '名額（此處）／位子'},
                {'nl': 'zich inschrijven', 'zh': '報名、登記'},
                {'nl': 'het lokaal', 'zh': '教室'},
            ],
            'patterns': [
                {'nl': 'Er zijn nog ... plaatsen', 'zh': '還剩……個名額',
                 'note': 'er zijn = 有（存在句）。'},
                {'nl': 'Komt u om ... naar ... als u ...', 'zh': '如果您要……，請於……到……',
                 'note': '祈使句 + als 條件子句。'},
            ],
            'questions': [
                {'n': 5, 't': '8:59',
                 'q_nl': 'Julio wil Nederlands 3 volgen. Hoeveel plaatsen zijn er nog?',
                 'q_zh': 'Julio 想上 Nederlands 3，這門課還剩幾個名額？',
                 'options': [('Eén', '一個'), ('Twee', '兩個'), ('Drie', '三個'), ('Geen', '沒有了')],
                 'answer': 1,
                 'source': [('8:25', 'De cursus Nederlands 3 zit bijna vol.', 'Nederlands 3 這門課快額滿了。'),
                            ('8:30', 'Er zijn nog twee plaatsen.', '還剩兩個名額。')],
                 'explain': '通知說 Nederlands 3「快滿了，還剩兩個名額」。題目鎖定 N3，就只聽 N3 那段。',
                 'trap': 'Nederlands 2「還有充足名額（voldoende plaatsen）」是干擾——但 Julio 要的是 N3。'},
                {'n': 6, 't': '10:19',
                 'q_nl': 'Waar kan hij zich aanmelden?',
                 'q_zh': '他要去哪裡報名（上 Nederlands 3）？',
                 'options': [('In lokaal 1', '1 號教室'), ('In lokaal 2', '2 號教室'),
                             ('In lokaal 5', '5 號教室'), ('In lokaal 15', '15 號教室')],
                 'answer': 3,
                 'source': [('8:33', 'Komt u om 1 uur naar lokaal 15 als u deze cursus wilt volgen.',
                             '想上這門課（N3），請一點到 15 號教室。')],
                 'explain': '針對 Nederlands 3，通知說「到 15 號教室」。',
                 'trap': '「inschrijven（報名）」這個字其實出現在 Nederlands 2 那段（lokaal 5）。聽到熟悉字就選會中陷阱——要鎖定 Julio 要的 N3。'},
            ],
        },
        {
            'title_zh': '鄰居在聊封路', 'title_nl': 'De buren van Amina praten over de afgesloten straat',
            'kind': '對話', 'dialogue': (105, 111),
            'context_zh': 'Amina 在社區活動中心，聽到鄰居們在討論他們的街道被封起來施工的事。',
            'vocab': [
                {'nl': 'afgesloten', 'zh': '被封閉的'},
                {'nl': 'de weg repareren', 'zh': '修路'},
                {'nl': 'gaten in de weg', 'zh': '路上的坑洞'},
                {'nl': 'de verlichting', 'zh': '照明（路燈）'},
                {'nl': 'tijdelijk', 'zh': '暫時的'},
            ],
            'patterns': [
                {'nl': 'Het is onhandig dat ...', 'zh': '……很不方便',
                 'note': 'dat 引導子句，動詞丟到句尾。'},
                {'nl': 'blijft dicht tot ...', 'zh': '一直關到……為止',
                 'note': 'tot + 時間點 = 期限。'},
            ],
            'questions': [
                {'n': 7, 't': '11:44',
                 'q_nl': 'Waarom is de straat van Amina afgesloten?',
                 'q_zh': 'Amina 家的街道為什麼被封起來？',
                 'options': [('Om de verlichting te maken', '為了裝路燈'),
                             ('Om de weg te repareren', '為了修路'),
                             ('Om parkeerplaatsen te maken', '為了蓋停車位')],
                 'answer': 1,
                 'source': [('11:11', 'het is wel goed dat ze de weg weer helemaal mooi maken',
                             '他們把路重新整修好，這倒是好事'),
                            ('11:16', 'Er zaten zoveel gaten in.', '路上之前有好多坑洞。')],
                 'explain': '鄰居說「他們在把路修好，之前有好多坑洞」——封路的原因是修路。',
                 'trap': '路燈、停車位 都被明說「沒有在做」（geen nieuwe verlichting／niet eens nieuwe parkeerplaatsen）。聽到地名／名詞別急著選。'},
                {'n': 8, 't': '13:09',
                 'q_nl': 'Wanneer gaat de straat van Amina weer open?',
                 'q_zh': 'Amina 家的街道什麼時候會重新開放？',
                 'options': [('Volgende week', '下週'), ('Over een maand', '一個月後'),
                             ('Over zes weken', '六週後')],
                 'answer': 2,
                 'source': [('13:01', 'die straat blijft dicht tot eind volgende maand',
                             '那條街要封到下個月底'),
                            ('13:04', 'Maar dat duurt nog 6 weken.', '那還要六週。')],
                 'explain': '一個鄰居先猜「下週」，馬上被另一個糾正「Nee joh...」——封到下月底，還要六週。',
                 'trap': '「Volgende week」是被講出來、但隨即被否定的錯誤資訊。對話題常見：先給錯的，再更正。'},
            ],
        },
        {
            'title_zh': '醫院淹水的新聞', 'title_nl': 'Farah kijkt naar het nieuws over het ziekenhuis',
            'kind': '新聞', 'dialogue': (130, 142),
            'context_zh': 'Farah 在看新聞：阿姆斯特丹南區一家醫院的水管破裂，造成淹水。',
            'vocab': [
                {'nl': 'de waterleiding', 'zh': '水管／供水管線'},
                {'nl': 'overstroomd', 'zh': '被淹沒的'},
                {'nl': 'de begane grond', 'zh': '一樓（地面層）'},
                {'nl': 'de verdieping', 'zh': '樓層'},
                {'nl': 'de afdeling', 'zh': '部門／科別'},
            ],
            'patterns': [
                {'nl': 'Vanaf ... is ... weer open', 'zh': '從……起，……重新開放',
                 'note': 'vanaf + 時間點 = 起始時間。'},
                {'nl': 'U kunt het beste ...', 'zh': '您最好是……',
                 'note': '給建議的固定句型。'},
            ],
            'questions': [
                {'n': 9, 't': '14:40',
                 'q_nl': 'Welke patiënten zijn naar een andere plaats gebracht?',
                 'q_zh': '哪些病人被移到別的地方？',
                 'options': [('Alleen de patiënten van de begane grond', '只有一樓的病人'),
                             ('Alleen de patiënten van de eerste verdieping', '只有二樓的病人'),
                             ('Alleen de patiënten van de tweede verdieping', '只有三樓的病人'),
                             ('Alle patiënten van het ziekenhuis', '醫院全部的病人')],
                 'answer': 1,
                 'source': [('13:46', 'De begane grond van het ziekenhuis is helemaal overstroomd. Gelukkig lagen daar geen patiënten.',
                             '醫院一樓全淹了。還好那裡沒有病人。'),
                            ('13:55', 'Alle patiënten op de eerste verdieping zijn wel naar een andere plek gebracht.',
                             '二樓（eerste verdieping）的病人則都被移走了。')],
                 'explain': '一樓淹水但「沒有病人」；被移走的是「eerste verdieping」的病人。荷文 eerste verdieping = 我們說的二樓。',
                 'trap': 'begane grond 是淹水的地方但沒病人；tweede verdieping 是他們被移「去」的地方。三個樓層都被提到，要聽清楚動作對應哪一層。'},
                {'n': 10, 't': '16:22',
                 'q_nl': 'Wanneer gaan alle afdelingen van het ziekenhuis weer open?',
                 'q_zh': '醫院所有科別什麼時候全部重新開放？',
                 'options': [('Dinsdag', '星期二'), ('Donderdag', '星期四'), ('Vrijdag', '星期五')],
                 'answer': 2,
                 'source': [('14:20', 'Vanaf vrijdag is het hele ziekenhuis weer open.',
                             '從星期五起，整間醫院重新開放。')],
                 'explain': '「Vanaf vrijdag is het hele ziekenhuis weer open」——星期五全院開放。',
                 'trap': 'dinsdag 是市府「一開始」說的修復日（後來改口）；donderdag 是水管修好的日子。全院開放是星期五。三個都是新聞裡的真實日期，要對準問的是哪件事。'},
                {'n': 11, 't': '17:54',
                 'q_nl': 'Savina is op treinstation Zuid. Hoe kan ze het beste naar het ziekenhuis gaan?',
                 'q_zh': 'Savina 在南站，她最好怎麼去醫院？',
                 'options': [('Met de tram', '搭電車'), ('Met de bus', '搭公車'), ('Lopend', '走路')],
                 'answer': 2,
                 'source': [('14:35', 'U kunt het beste vanaf treinstation Zuid naar het ziekenhuis lopen.',
                             '您最好從南站走路到醫院。')],
                 'explain': '新聞直接給建議：從南站「走路（lopen）」過去最好。',
                 'trap': '公車「voorlopig geen bussen（暫時停駛）」、電車「kom niet met de tram（別搭）」都被否定掉了。'},
            ],
        },
        {
            'title_zh': '電話語音點餐', 'title_nl': 'Een klant spreekt een bestelling in op de voicemail',
            'kind': '語音留言', 'dialogue': (187, 195),
            'context_zh': 'Hamza 在一家批發商工作。一位客人（Snackbar de Hoek 的 Gerritsen 先生）在語音信箱留下訂單。',
            'vocab': [
                {'nl': 'de groothandel', 'zh': '批發商'},
                {'nl': 'de bestelling', 'zh': '訂單'},
                {'nl': 'de patat (Franse / dikke)', 'zh': '薯條（細的／粗的）'},
                {'nl': 'de rekening', 'zh': '帳單'},
                {'nl': 'het postadres / huisadres', 'zh': '通訊地址／住家地址'},
            ],
            'patterns': [
                {'nl': 'Ik wil graag ... bestellen', 'zh': '我想訂……',
                 'note': 'graag 讓語氣禮貌。'},
                {'nl': 'Niet ..., maar ...', 'zh': '不是……，而是……',
                 'note': '聽力陷阱最愛的對比句，答案永遠在 maar 後面。'},
            ],
            'questions': [
                {'n': 12, 't': '19:20',
                 'q_nl': 'Welke patat bestelt meneer Gerritsen?',
                 'q_zh': 'Gerritsen 先生訂哪一種薯條？',
                 'options': [('Patat die hij zelf nog moet snijden', '要自己切的薯條'),
                             ('Dikke patat', '粗薯條'), ('Franse patat', '法式（細）薯條')],
                 'answer': 2,
                 'source': [('18:42', 'Niet van die dikke, die moet ik zelf dan nog snijden.',
                             '不要那種粗的，那種我還得自己切。'),
                            ('18:47', 'Maar van die Franse zeg maar, die dunne.',
                             '要法式的那種，就是細的。')],
                 'explain': '經典「Niet ..., maar ...」句型：不要粗的（自己切），要法式細薯條。答案在 maar 後面。',
                 'trap': '「dikke」「zelf snijden」都被他明確說「不要」。聽到先出現的字就選會錯。'},
                {'n': 13, 't': '20:44',
                 'q_nl': 'Welke cola bestelt meneer Gerritsen?',
                 'q_zh': 'Gerritsen 先生訂哪一種可樂？',
                 'options': [('Zes dozen grijze blikjes', '六箱灰色罐'),
                             ('Zes dozen zwarte blikjes', '六箱黑色罐'),
                             ('Tien dozen grijze blikjes', '十箱灰色罐'),
                             ('Tien dozen zwarte blikjes', '十箱黑色罐')],
                 'answer': 2,
                 'source': [('18:59', 'graag tien dozen cola blikjes',
                             '可樂罐請給我十箱'),
                            ('18:59', 'Maar dan niet van die zwarte, maar die grijze Cola Light.',
                             '不要黑色那種，要灰色的 Cola Light。')],
                 'explain': '數量「tien dozen（十箱）」+ 顏色「niet zwarte, maar grijze（不要黑、要灰）」。兩個資訊都要抓對。',
                 'trap': '「zes dozen」是薯條的數量；黑色是他不要的顏色。數量和顏色各有一個干擾。'},
                {'n': 14, 't': '22:20',
                 'q_nl': 'Waar moet Hamza de rekening naartoe sturen?',
                 'q_zh': 'Hamza 要把帳單寄到哪裡？',
                 'options': [('Naar het huisadres', '寄到住家地址'),
                             ('Naar de Snackbar', '寄到小吃店'),
                             ('Naar het postadres', '寄到通訊地址')],
                 'answer': 2,
                 'source': [('19:07', 'Maar de rekening wel naar mijn postadres sturen graag.',
                             '但帳單請寄到我的通訊地址。'),
                            ('19:11', 'Niet zoals de vorige keer naar mijn huisadres.',
                             '不要像上次那樣寄到我的住家地址。')],
                 'explain': '貨（bestelling）送到小吃店，但帳單（rekening）要寄到 postadres，而非上次的 huisadres。',
                 'trap': '題目問「帳單」。貨送 Snackbar 是另一件事；huisadres 是他明說不要的。'},
            ],
        },
        {
            'title_zh': '老師講評作文', 'title_nl': 'Enrico praat met de docent over zijn brief',
            'kind': '對話', 'dialogue': (235, 252),
            'context_zh': 'Melvin 在上英文課。他的同學 Enrico 和老師討論寫作作業（一封信）。',
            'vocab': [
                {'nl': 'de schrijfopdracht', 'zh': '寫作作業'},
                {'nl': 'de volgorde van de woorden', 'zh': '字詞順序（語序）'},
                {'nl': 'de spelfout / de spelling', 'zh': '拼字錯誤／拼字'},
                {'nl': 'het werkwoord', 'zh': '動詞'},
                {'nl': 'de medecursist', 'zh': '同班同學'},
            ],
            'patterns': [
                {'nl': 'Je hebt bijna geen fouten gemaakt met ...', 'zh': '你在……幾乎沒犯錯',
                 'note': 'fouten maken met = 在某方面犯錯。'},
                {'nl': 'Misschien kan iemand ... doorlezen', 'zh': '也許可以請人……看過一遍',
                 'note': 'doorlezen = 從頭讀過、檢查。'},
            ],
            'questions': [
                {'n': 15, 't': '24:18',
                 'q_nl': 'Waarmee heeft Enrico de meeste fouten gemaakt in zijn brief?',
                 'q_zh': 'Enrico 在信裡哪方面錯最多？',
                 'options': [('Met de volgorde van de woorden', '字詞順序'),
                             ('Met de spelling', '拼字'),
                             ('Met de werkwoorden', '動詞')],
                 'answer': 1,
                 'source': [('23:12', 'niet alle woorden zijn goed geschreven',
                             '不是每個字都拼對'),
                            ('23:18', 'Kijk, er zitten nog best veel spelfouten in.',
                             '你看，裡面還有不少拼字錯誤。')],
                 'explain': '老師說「還有不少拼字錯誤（best veel spelfouten）」——best veel = 相當多。',
                 'trap': '語序「bijna geen fouten（幾乎沒錯）」、動詞「soms een foutje（偶爾小錯）」。題目問「最多」，三個方面都被提到，要比較程度。'},
                {'n': 16, 't': '26:19',
                 'q_nl': 'Welk advies over brievenschrijven geeft de docent aan Enrico?',
                 'q_zh': '關於寫信，老師給 Enrico 什麼建議？',
                 'options': [('Laat je brief controleren door iemand anders', '請別人幫你檢查信'),
                             ('Gebruik een woordenboek tijdens het schrijven', '寫的時候用字典'),
                             ('Lees je brief nog een keer door als je klaar bent', '寫完再自己讀一遍')],
                 'answer': 0,
                 'source': [('23:32', 'Misschien kan iemand je brief nog eens doorlezen als hij af is.',
                             '信寫完後，也許可以請人再看過一遍。'),
                            ('23:45', 'Je kunt je brief aan een medecursist geven ... Die kan er dan nog fouten uithalen.',
                             '你可以把信給同學……他可以幫你挑出錯誤。')],
                 'explain': '老師的建議是「請別人（同學）幫你檢查、挑錯」。',
                 'trap': '字典是 Enrico 自己提到的（「我字典裡查不到」），不是老師的建議。誰說的要聽清楚。'},
            ],
        },
        {
            'title_zh': '朋友的語音留言（約吃飯看電影）', 'title_nl': 'Sonja luistert naar een voicemailbericht van Zineb',
            'kind': '語音留言', 'dialogue': (282, 293),
            'context_zh': 'Sonja 聽朋友 Zineb 留在語音信箱的訊息：原本約的披薩店關了，要改約。',
            'vocab': [
                {'nl': 'het voicemailbericht', 'zh': '語音留言'},
                {'nl': 'afgesproken', 'zh': '約好的（afspreken 的過去分詞）'},
                {'nl': 'gesloten', 'zh': '關閉的、沒營業的'},
                {'nl': 'reserveren', 'zh': '訂位'},
                {'nl': 'terugbellen', 'zh': '回電'},
            ],
            'patterns': [
                {'nl': 'We hadden afgesproken om ... te ...', 'zh': '我們原本約好要……',
                 'note': 'hadden afgesproken 過去完成式，表「原本的安排」（後面常被推翻）。'},
                {'nl': 'Vind je het leuk om ... te ...?', 'zh': '你想不想……？',
                 'note': '禮貌邀約句。'},
            ],
            'questions': [
                {'n': 17, 't': '28:15',
                 'q_nl': 'Waar wil Zineb eten?',
                 'q_zh': 'Zineb 想在哪裡吃飯？',
                 'options': [('Bij Sonja thuis', '在 Sonja 家'),
                             ('In de bioscoop', '在電影院'),
                             ('In een restaurant', '在一家餐廳')],
                 'answer': 2,
                 'source': [('27:23', 'We hadden afgesproken om naar die pizzeria te gaan, maar hij is gesloten.',
                             '我們本來約去那家披薩店，但它沒開。'),
                            ('27:30', 'Morgenavond is het restaurant wel open.',
                             '明天晚上那家餐廳就有開了。')],
                 'explain': '披薩店關了，改成明晚去「restaurant」吃。',
                 'trap': 'thuis 是 Zineb 要去「接」Sonja 的地方；bioscoop 是飯後看電影的地方。吃飯地點是 restaurant。'},
                {'n': 18, 't': '29:53',
                 'q_nl': 'Hoe laat wil Zineb afspreken?',
                 'q_zh': 'Zineb 想約幾點？',
                 'options': [('Vanavond om zes uur', '今晚六點'),
                             ('Vanavond om zeven uur', '今晚七點'),
                             ('Morgenavond om zes uur', '明晚六點'),
                             ('Morgenavond om zeven uur', '明晚七點')],
                 'answer': 3,
                 'source': [('27:30', 'Morgenavond is het restaurant wel open.', '明天晚上餐廳有開。'),
                            ('27:34', 'Kun jij dan toevallig ook? Om zeven uur?',
                             '你那時候也可以嗎？七點？')],
                 'explain': '兩個資訊要組合：日子「morgenavond（明晚）」+ 時間「om zeven uur（七點）」。',
                 'trap': '今晚（vanavond）是原本的計畫、已作廢；六點根本沒出現。要把「哪天」和「幾點」分開聽再合起來。'},
                {'n': 19, 't': '31:39',
                 'q_nl': 'Wie is Moerad?',
                 'q_zh': 'Moerad 是誰？',
                 'options': [('Een broer van Zineb', 'Zineb 的哥哥／弟弟'),
                             ('Een collega van Zineb', 'Zineb 的同事'),
                             ('Een vriend van Zineb', 'Zineb 的朋友')],
                 'answer': 0,
                 'source': [('27:46', 'ik ga morgenavond ook nog met mijn broer Moerad naar de film',
                             '明晚我還要跟我哥哥 Moerad 去看電影')],
                 'explain': 'Zineb 說「mijn broer Moerad」——我哥哥 Moerad。broer = 兄弟。',
                 'trap': '人物關係題只要抓住名字前後那個詞（mijn broer），不必聽懂整句。'},
            ],
        },
        {
            'title_zh': '寫作課老師交代事項', 'title_nl': 'Paula luistert naar haar docent verhalen schrijven',
            'kind': '對話', 'dialogue': (335, 349), 'no_questions': True,
            'context_zh': 'Paula 在上故事寫作課，老師交代作業講評與隔天的自然戶外計畫。（本場景的考題影片未收錄，僅附對話與重點供額外聽力練習。）',
            'vocab': [
                {'nl': 'de huiswerkopdracht', 'zh': '回家作業'},
                {'nl': 'het natuurproject', 'zh': '自然主題的專題'},
                {'nl': 'het schrijfblok', 'zh': '寫字本／筆記本'},
                {'nl': 'de stadsboerderij', 'zh': '城市農場（市區裡的小型農場）'},
            ],
            'patterns': [
                {'nl': 'Let op. We spreken ... af', 'zh': '注意，我們約……',
                 'note': 'Let op = 請注意（要聽重點了）。'},
                {'nl': 'Iedereen moet zijn eigen ... meenemen', 'zh': '每個人都要帶自己的……',
                 'note': 'meenemen = 隨身帶。'},
            ],
            'questions': [],
        },
        {
            'title_zh': '國王節活動安排', 'title_nl': 'Mila en Carla praten met de leraar over Koningsdag',
            'kind': '對話', 'dialogue': (372, 387),
            'context_zh': 'Mila 和 Carla 的孩子在唸小學。兩人和老師討論國王節（4 月 27 日）當天的家長協助安排。',
            'vocab': [
                {'nl': 'het Koningsdagontbijt', 'zh': '國王節早餐'},
                {'nl': 'klaarzetten', 'zh': '把東西擺設、布置好'},
                {'nl': 'boodschappen doen', 'zh': '採買（買菜）'},
                {'nl': 'de wedstrijd', 'zh': '比賽'},
                {'nl': 'de fiets versieren', 'zh': '裝飾腳踏車'},
            ],
            'patterns': [
                {'nl': 'half negen / half tien', 'zh': '八點半／九點半',
                 'note': '荷文 half + 整點 = 該整點的「前半小時」，half negen = 8:30！'},
                {'nl': 'Dat duurt wel een half uur', 'zh': '那大概要花半小時',
                 'note': 'duren = 持續、花（時間）。'},
            ],
            'questions': [
                {'n': 20, 't': '37:37',
                 'q_nl': 'Wat moeten Mila en Carla op 27 april doen?',
                 'q_zh': 'Mila 和 Carla 在 4 月 27 日要做什麼？',
                 'options': [('Helpen met boodschappen doen', '幫忙採買'),
                             ('Helpen bij het ontbijt', '幫忙早餐'),
                             ('Helpen bij de sportdag', '幫忙運動會')],
                 'answer': 1,
                 'source': [('36:15', 'Jullie gaan helpen bij het Koningsdagontbijt op vrijdag 27 april.',
                             '你們 4 月 27 日星期五要來幫忙國王節早餐。')],
                 'explain': '老師一開口就說「你們要幫忙 Koningsdagontbijt（國王節早餐）」。',
                 'trap': '採買是 Giovanni 的媽媽負責（「Dat doet de moeder van Giovanni」）；運動會沒提到。'},
                {'n': 21, 't': '39:45',
                 'q_nl': 'Hoe laat moeten Mila en Carla op 27 april op school zijn?',
                 'q_zh': 'Mila 和 Carla 4 月 27 日幾點要到學校？',
                 'options': [('Om acht uur', '八點'), ('Om half negen', '八點半'),
                             ('Om half tien', '九點半')],
                 'answer': 0,
                 'source': [('36:41', 'Dus de kinderen komen om half negen.', '所以小孩八點半到。'),
                            ('36:46', 'Hoe laat moeten we alles klaarzetten? ... dat duurt wel een half uur',
                             '我們幾點要把東西擺好？……那大概要半小時'),
                            ('36:52', 'Ja, dan zijn wij er om acht uur.', '那我們八點就到。')],
                 'explain': '小孩 8:30 到，布置要花半小時 → 家長要 8:00 到。要自己做一步推算。',
                 'trap': 'half negen（8:30）是「小孩」到的時間，不是家長。half tien（9:30）是去運動場的時間。'},
                {'n': 22, 't': '41:54',
                 'q_nl': 'Waarmee eindigt de Koningsdag?',
                 'q_zh': '國王節當天以什麼活動結束？',
                 'options': [('Met een dans', '跳舞'), ('Met een lied', '一首歌'),
                             ('Met een wedstrijd', '一場比賽'), ('Met een spel', '一個遊戲')],
                 'answer': 2,
                 'source': [('37:25', 'En aan het eind van de dag is er een wedstrijd. Dan gaan de kinderen hun fiets versieren.',
                             '一天的最後有一場比賽，小孩會裝飾自己的腳踏車。')],
                 'explain': '「aan het eind van de dag（一天的最後）is er een wedstrijd」——以比賽收尾。',
                 'trap': '跳舞、唱歌是「一開始（Eerst）」的活動；遊戲在中間。問的是「結束」。'},
            ],
        },
    ],
}


# ─────────────────────────────────────────────────────────────────────
# PART 2 — EXAMEN A2 luisteren 2026 inburgering PART 2  (AMVy2zPNLso)
# ─────────────────────────────────────────────────────────────────────
PART2 = {
    'video_id': 'AMVy2zPNLso',
    'exam_type': 'A2 Luisteren · Inburgering',
    'intro': (
        '本片有幾題的題目字幕是「畫面顯示、沒有念出聲」（考試指令是 Lees eerst '
        'de vraag — 先「讀」題目），自動轉錄抓不到。這些題目已根據選項與原文'
        '忠實重建，並標註「題幹重建」。其餘結構與 PART 1 相同。'
    ),
    'scenarios': [
        {
            'title_zh': '到市政府辦出生登記', 'title_nl': 'Eren en Mark bij de gemeente',
            'kind': '對話', 'dialogue': (2, 10),
            'context_zh': 'Eren 陪朋友 Mark 到市政府。Mark 昨天生了兒子，要辦出生登記。',
            'vocab': [
                {'nl': 'aangifte doen van de geboorte', 'zh': '辦理出生登記'},
                {'nl': 'het legitimatiebewijs', 'zh': '身分證件'},
                {'nl': 'het trouwboekje', 'zh': '結婚證書（小冊）'},
                {'nl': 'een afspraak maken', 'zh': '預約'},
                {'nl': 'aan de balie', 'zh': '在櫃台'},
            ],
            'patterns': [
                {'nl': 'U kunt tot ... na ... aangifte doen', 'zh': '您最晚可在……之後……內辦登記',
                 'note': 'tot ... na ... = 期限。'},
                {'nl': 'Dan moet u ook ... meenemen', 'zh': '那您還要帶……來',
                 'note': 'meenemen 為可分動詞，mee 丟句尾。'},
            ],
            'questions': [
                {'n': 1, 't': '1:11',
                 'q_nl': 'Waarom is Mark bij de gemeente?',
                 'q_zh': 'Mark 為什麼來市政府？',
                 'options': [('Hij wil een geboorte aangeven', '他要辦出生登記'),
                             ('Hij is zijn legitimatiebewijs kwijt', '他弄丟了身分證件'),
                             ('Hij gaat binnenkort trouwen', '他快要結婚了')],
                 'answer': 0,
                 'source': [('0:26', 'Ik heb een zoon gekregen, gisteren.', '我昨天生了一個兒子。'),
                            ('0:31', 'U wilt dus aangifte doen van de geboorte.',
                             '所以您是要辦出生登記。')],
                 'explain': 'Mark 一開口說「昨天生了兒子」，櫃台人員確認「您要辦出生登記」——這就是他來的目的。',
                 'trap': '證件是「忘了帶（vergeten）」不是弄丟；結婚是櫃台問「是否已婚」，他已婚——兩者都只是辦事過程的細節。'},
                {'n': 2, 't': '2:36',
                 'q_nl': 'Wanneer kan Mark terugkomen bij de gemeente?',
                 'q_zh': 'Mark 什麼時候可以再回來市政府辦？',
                 'options': [('Vanmiddag', '今天下午'), ('Morgenochtend', '明天早上'),
                             ('Over drie dagen', '三天後')],
                 'answer': 1,
                 'source': [('0:43', 'het mag morgen ook nog. Want vanmiddag zijn we gesloten.',
                             '明天辦也還可以。因為今天下午我們不營業。'),
                            ('0:52', 'Morgen zijn we tot twaalf uur open.',
                             '明天我們開到十二點。')],
                 'explain': '今天下午關門，但明天「開到十二點」——所以明天早上回來辦。',
                 'trap': 'vanmiddag（今天下午）被明說「gesloten（關門）」；登記期限是出生後兩天內，不是三天。'},
            ],
        },
        {
            'title_zh': '人力派遣公司的影片', 'title_nl': 'Yassir bekijkt een filmpje van uitzendbureau Kracht',
            'kind': '廣告影片', 'dialogue': (45, 60),
            'context_zh': 'Yassir 想透過派遣公司 Kracht 找工作，已經報名了。他在看公司的介紹影片。',
            'vocab': [
                {'nl': 'het uitzendbureau', 'zh': '人力派遣公司'},
                {'nl': 'het kennismakingsgesprek', 'zh': '初次面談（認識彼此）'},
                {'nl': 'de schoonmaak / de beveiliging / de productie', 'zh': '清潔／保全／生產'},
                {'nl': 'de avondopleiding tot leidinggevende', 'zh': '晉升主管的夜間培訓'},
                {'nl': 'stage lopen', 'zh': '實習'},
            ],
            'patterns': [
                {'nl': 'U krijgt daarvoor een uitnodiging per ...', 'zh': '為此您會透過……收到邀請',
                 'note': 'per e-mail / per brief = 透過某管道。'},
                {'nl': 'het is fijn als ..., maar dat hoeft niet', 'zh': '如果……很好，但不是必須',
                 'note': 'hoeft niet = 不需要、非必要——常是陷阱關鍵。'},
            ],
            'questions': [
                {'n': 3, 't': '~6:35', 'reconstructed': True,
                 'q_nl': 'Hoe krijgt Yassir de datum en tijd van het gesprek?',
                 'q_zh': 'Yassir 會怎麼收到面談的日期與時間？',
                 'options': [('Via een e-mail', '透過電子郵件'),
                             ('Via een brief', '透過信件')],
                 'answer': 0,
                 'source': [('5:00', 'En u heeft binnenkort een kennismakingsgesprek.',
                             '您近期會有一場初次面談。'),
                            ('5:07', 'U krijgt daarvoor een uitnodiging per e-mail met de datum en de tijd.',
                             '為此您會收到一封電子郵件邀請，上面有日期和時間。')],
                 'explain': '影片說「per e-mail ... met de datum en de tijd」——日期時間透過 e-mail 通知。',
                 'trap': 'brief（信件）只是干擾選項，原文只出現 e-mail。'},
                {'n': 4, 't': '~9:00', 'reconstructed': True,
                 'q_nl': 'Wat heeft Yassir nodig om in de schoonmaak te werken?',
                 'q_zh': 'Yassir 要做清潔工作需要具備什麼？',
                 'options': [('Ervaring met schoonmaakwerk', '清潔工作的經驗'),
                             ('Nederlands spreken op A2 niveau', '荷蘭語達 A2 程度')],
                 'answer': 1,
                 'source': [('5:24', 'Voor de schoonmaak en productie moet u Nederlands spreken op A2 niveau.',
                             '清潔和生產的工作，您必須會說 A2 程度的荷蘭語。'),
                            ('5:35', 'Ook is het fijn als u ervaring heeft met het werk, maar dat hoeft niet.',
                             '有相關工作經驗也不錯，但這不是必須的。')],
                 'explain': '清潔工作「moet（必須）A2 荷語」；經驗則是「fijn ... maar dat hoeft niet（有也好，但非必要）」。必須的是 A2。',
                 'trap': '「ervaring」聽起來很像條件，但緊接著的 hoeft niet 把它否定成「非必要」。'},
            ],
        },
        {
            'title_zh': '電話語音報路', 'title_nl': 'Roman luistert naar een voicemail van Erik',
            'kind': '語音留言', 'dialogue': (105, 115),
            'context_zh': 'Roman 要去市政廳。朋友 Erik 在他的語音信箱留言，告訴他怎麼走、在哪停車。',
            'vocab': [
                {'nl': 'linksaf / rechtsaf / rechtdoor', 'zh': '左轉／右轉／直走'},
                {'nl': 'de brug', 'zh': '橋'},
                {'nl': 'de parkeerplaats voor bezoekers', 'zh': '訪客停車場'},
                {'nl': 'de parkeergarage', 'zh': '室內停車場'},
                {'nl': 'aan de overkant van de weg', 'zh': '在馬路對面'},
            ],
            'patterns': [
                {'nl': 'Bij ... ga je naar rechts', 'zh': '到了……你往右',
                 'note': '報路：bij + 地標 + 方向。'},
                {'nl': '... is het handigste', 'zh': '……最方便',
                 'note': '最高級 + denk ik（我覺得）= 給建議。'},
            ],
            'questions': [
                {'n': 5, 't': '12:50',
                 'q_nl': 'Wat moet hij doen bij de groene brug?',
                 'q_zh': '到了綠色的橋，他要怎麼走？',
                 'options': [('Hij moet linksaf', '左轉'), ('Hij moet rechtsaf', '右轉'),
                             ('Hij moet rechtdoor', '直走'), ('Hij moet parkeren', '停車')],
                 'answer': 1,
                 'source': [('12:09', 'En dan bij de groene brug ga je naar rechts.',
                             '然後到綠色的橋，你往右。')],
                 'explain': '「bij de groene brug ga je naar rechts」——綠橋處往右（rechtsaf）。',
                 'trap': 'linksaf 是「從家裡出發」的第一步；rechtdoor 是綠橋「之後」的動作。報路題要鎖定問的是哪個地標。'},
                {'n': 6, 't': '16:04',
                 'q_nl': 'Waar kan hij het beste parkeren?',
                 'q_zh': '他最好停在哪裡？',
                 'options': [('In de parkeergarage', '室內停車場'),
                             ('Op de parkeerplaats voor bezoekers', '訪客停車場'),
                             ('Aan de overkant van de weg', '馬路對面')],
                 'answer': 1,
                 'source': [('12:38', 'Maar die parkeerplaats voor bezoekers is wel het handigste, denk ik.',
                             '不過我覺得訪客停車場最方便。')],
                 'explain': '三個地方都能停，但 Erik 說「parkeerplaats voor bezoekers ... het handigste（最方便）」。',
                 'trap': '室內停車場、馬路對面 都是「也可以（ook）」的選項。題目問「最好」，要聽 het handigste。'},
            ],
        },
        {
            'title_zh': '新工作：怎麼訂用品', 'title_nl': 'De baas van Nabil legt uit hoe je materiaal bestelt',
            'kind': '對話', 'dialogue': (154, 161),
            'context_zh': 'Nabil 有了新工作。老闆告訴他需要訂用品（例如筆）時該怎麼做。',
            'vocab': [
                {'nl': 'materiaal bestellen', 'zh': '訂購用品／物料'},
                {'nl': 'de afdeling Inkoop', 'zh': '採購部門'},
                {'nl': 'het formulier invullen', 'zh': '填表格'},
                {'nl': 'inleveren', 'zh': '繳交、送交'},
                {'nl': 'het postvak', 'zh': '信件格、信箱格'},
            ],
            'patterns': [
                {'nl': 'Als je iets wilt bestellen, vul je ... in', 'zh': '如果你想訂東西，就填……',
                 'note': 'als 子句在前，主句動詞緊接其後。'},
                {'nl': 'Inkoop zit op de tweede verdieping', 'zh': '採購部在三樓',
                 'note': 'zitten 口語可表「位於」。'},
            ],
            'questions': [
                {'n': 7, 't': '17:23',
                 'q_nl': 'Waar zit de afdeling Inkoop?',
                 'q_zh': '採購部（Inkoop）在哪裡？',
                 'options': [('In kamer 2.2', '2.2 室'),
                             ('In kamer 2.3 naast de kantine', '2.3 室，員工餐廳旁')],
                 'answer': 1,
                 'source': [('16:54', 'Inkoop zit op de tweede verdieping, kamer 2.3.',
                             '採購部在三樓，2.3 室。'),
                            ('16:59', 'Je kijkt zo naar binnen vanuit de kantine.',
                             '你從員工餐廳就能看進去。')],
                 'explain': '採購部在 kamer 2.3，從員工餐廳就看得到。',
                 'trap': '2.2 室是 Verkoop（銷售部），就在採購部隔壁——兩個房號很接近，要聽清楚。'},
                {'n': 8, 't': '~18:55', 'reconstructed': True,
                 'q_nl': 'Hoe moet Nabil iets bestellen?',
                 'q_zh': 'Nabil 要訂東西時該怎麼做？',
                 'options': [('Even langslopen bij de afdeling Inkoop', '親自走一趟採購部'),
                             ('De afdeling Inkoop bellen met de bestelling', '打電話給採購部下訂'),
                             ('De bestelling naar de afdeling Inkoop mailen', '把訂單 email 給採購部')],
                 'answer': 0,
                 'source': [('17:04', 'Als je iets wilt bestellen, vul je dit formulier in.',
                             '如果你想訂東西，就填這張表格。'),
                            ('17:04', 'Dat lever je dan in bij Inkoop.',
                             '然後把表格送去採購部。')],
                 'explain': '下訂流程是：填表格 →「inleveren bij Inkoop」親自送去採購部。',
                 'trap': '打電話、寄 email 是「採購部通知你貨到了」的方式（bellen / mailtje），不是你下訂的方式——方向相反。'},
            ],
        },
        {
            'title_zh': '同學聊怎麼準備考試', 'title_nl': 'Mira en Chris praten over de examens',
            'kind': '對話', 'dialogue': (195, 202),
            'context_zh': 'Julia 在上廚師課程。她的同學 Mira 和 Chris 在聊接下來一堆考試怎麼準備。',
            'vocab': [
                {'nl': 'een drukke tijd', 'zh': '忙碌的時期'},
                {'nl': 'een planning maken', 'zh': '做規劃／排計畫'},
                {'nl': 'een tip geven', 'zh': '給建議、給訣竅'},
                {'nl': 'de vertraging', 'zh': '誤點、延誤'},
                {'nl': 'extra', 'zh': '額外的'},
            ],
            'patterns': [
                {'nl': 'Zorg dat je eerst ...', 'zh': '你要先確保／先把……做好',
                 'note': 'zorg dat = 給建議的祈使句。'},
                {'nl': 'Als ik je nog een tip mag geven, ...', 'zh': '容我再給你一個建議……',
                 'note': '帶出「第二個」建議——順序題的關鍵。'},
            ],
            'questions': [
                {'n': 9, 't': '21:53',
                 'q_nl': 'Welke tip geeft Chris als eerste aan Mira?',
                 'q_zh': 'Chris 給 Mira 的「第一個」建議是什麼？',
                 'options': [('Ga extra veel leren', '多花時間讀書'),
                             ('Leer in de bus en in de trein', '在公車和火車上讀書'),
                             ('Maak een planning', '做一份規劃')],
                 'answer': 2,
                 'source': [('21:21', 'Nou, weet je, zorg dat je eerst een goede planning maakt.',
                             '你知道嗎，先做好一份規劃。'),
                            ('21:29', 'En als ik je dan nog een tip mag geven: ga leren in de bus en in de trein.',
                             '容我再給你一個建議：在公車和火車上讀書。')],
                 'explain': 'Chris 第一個說的是「先做好 planning」。第二個建議用「nog een tip」帶出來——所以那是第二個。',
                 'trap': '在公車／火車上讀書 是第二個建議。題目問「als eerste（第一個）」，要聽順序詞 eerst / nog een。'},
                {'n': 10, 't': '23:29',
                 'q_nl': 'Wat zegt Chris over vertraging?',
                 'q_zh': '關於誤點，Chris 怎麼說？',
                 'options': [('Dan heb je extra tijd om te leren', '那你就有額外時間讀書'),
                             ('Dan heb je minder tijd om te leren', '那你讀書時間就變少'),
                             ('Dat je vaker vertraging hebt met de bus', '搭公車比較常誤點'),
                             ('Dat je vaker vertraging hebt met de trein', '搭火車比較常誤點')],
                 'answer': 0,
                 'source': [('21:36', 'die tijd ben je toch aan het wachten. Dan kan je heel veel extra doen.',
                             '反正那段時間你也在等。那你就能多做很多事。'),
                            ('21:41', 'Vooral als je zo vaak vertraging hebt.',
                             '尤其當你那麼常遇到誤點的時候。')],
                 'explain': 'Chris 把誤點講成「好事」：等車的時間拿來讀書，就有額外時間（extra tijd）。',
                 'trap': 'minder tijd（時間變少）正好相反；公車／火車哪個常誤點不是重點，他講的是「怎麼利用」誤點。'},
            ],
        },
        {
            'title_zh': '廣播路況報導', 'title_nl': 'Mario hoort een bericht over files op de radio',
            'kind': '廣播', 'dialogue': (228, 240),
            'context_zh': 'Mario 聽廣播，裡面在報高速公路的塞車（file）路況，最後還有一則火車的消息。',
            'vocab': [
                {'nl': 'de file', 'zh': '塞車、車陣'},
                {'nl': 'de snelweg', 'zh': '高速公路'},
                {'nl': 'het ongeluk', 'zh': '車禍、意外'},
                {'nl': 'de vrachtwagen', 'zh': '貨車、卡車'},
                {'nl': 'doorrijden', 'zh': '繼續行駛'},
            ],
            'patterns': [
                {'nl': 'Er staat een file van ... kilometer', 'zh': '有……公里長的車陣',
                 'note': 'staan 用於塞車「停在那裡」。'},
                {'nl': 'U kunt met de ... reizen', 'zh': '您可以搭……',
                 'note': 'reizen = 搭乘交通工具旅行。'},
            ],
            'questions': [
                {'n': 11, 't': '29:05',
                 'q_nl': 'Mario wil met de trein van Arnhem naar Utrecht. Wat kan hij het beste doen?',
                 'q_zh': 'Mario 想搭火車從 Arnhem 到 Utrecht，他最好怎麼辦？',
                 'options': [('Met een taxi reizen', '搭計程車'),
                             ('Via Apeldoorn reizen', '繞道 Apeldoorn'),
                             ('Met de NS-bus reizen', '搭國鐵接駁巴士')],
                 'answer': 2,
                 'source': [('27:00', 'Tussen de stations Arnhem en Utrecht rijden geen treinen.',
                             'Arnhem 和 Utrecht 兩站之間沒有火車。'),
                            ('27:04', 'U kunt met de NS-bussen reizen.',
                             '您可以改搭國鐵（NS）接駁巴士。')],
                 'explain': '這兩站之間沒火車，廣播建議改搭「NS-bussen（國鐵接駁巴士）」。',
                 'trap': '計程車、Apeldoorn 都沒被提到，是干擾。Apeldoorn 只是另一段塞車的地名。'},
            ],
        },
        {
            'title_zh': '新工作：接電話的規矩', 'title_nl': 'De baas legt Sophia de telefoonregels uit',
            'kind': '對話', 'dialogue': (301, 310),
            'context_zh': 'Sophia 第一天上新工作。老闆教她接電話的規矩：找總監、找採購部、同事午休時各該怎麼處理。',
            'vocab': [
                {'nl': 'voorgaan', 'zh': '優先、最重要'},
                {'nl': 'de telefoon opnemen', 'zh': '接電話'},
                {'nl': 'doorverbinden', 'zh': '（電話）轉接'},
                {'nl': 'in de agenda kijken', 'zh': '查行事曆'},
                {'nl': 'de beller', 'zh': '來電者'},
            ],
            'patterns': [
                {'nl': 'Als iemand ... wil spreken, dan ...', 'zh': '如果有人想找……，就……',
                 'note': '一連串「als ..., dan ...」規則句。'},
                {'nl': 'Vergeet ook niet ...', 'zh': '也別忘了……',
                 'note': 'vergeet niet = 提醒、別忘記。'},
            ],
            'questions': [
                {'n': 12, 't': '~30:35', 'reconstructed': True,
                 'q_nl': 'Iemand belt voor de directeur. Wat moet Sophia als eerste doen?',
                 'q_zh': '有人打電話找總監，Sophia 要「先」做什麼？',
                 'options': [('Een 1 toetsen', '按 1'), ('Een 4 toetsen', '按 4'),
                             ('In zijn agenda kijken', '查他的行事曆'),
                             ('Naar Evelien doorverbinden', '轉接給 Evelien')],
                 'answer': 2,
                 'source': [('33:01', 'Als iemand de directeur wil spreken, dan verbind je niet meteen door.',
                             '如果有人想找總監，你不要馬上轉接。'),
                            ('33:01', 'Je kijkt dan eerst in zijn agenda.',
                             '你要先查他的行事曆。')],
                 'explain': '規矩是「不要馬上轉接，先查行事曆（eerst in zijn agenda kijken）」。',
                 'trap': '按 1 是「查完行事曆、確認他有空之後」才做的下一步——順序不能顛倒。'},
                {'n': 13, 't': '~32:10', 'reconstructed': True,
                 'q_nl': 'Iemand belt voor de afdeling Inkoop. Wat moet Sophia doen?',
                 'q_zh': '有人打電話找採購部，Sophia 要做什麼？',
                 'options': [('Een 1 toetsen', '按 1'), ('Een 4 toetsen', '按 4'),
                             ('In de agenda kijken', '查行事曆')],
                 'answer': 1,
                 'source': [('33:06', 'Als er iemand belt voor de afdeling inkoop, die kun je meteen doorverbinden.',
                             '如果有人打來找採購部，你可以直接轉接。'),
                            ('33:13', 'Je toetst dan de 4.', '那就按 4。')],
                 'explain': '找採購部可以「直接轉接」，按 4。',
                 'trap': '按 1 是找總監時的動作；查行事曆也是針對總監。採購部 → 按 4。'},
                {'n': 14, 't': '33:36',
                 'q_nl': 'Evelien heeft pauze en Sophia neemt haar telefoon op. Wat moet je doen?',
                 'q_zh': 'Evelien 在午休，Sophia 替她接電話，這時要做什麼？',
                 'options': [('De naam en het nummer opschrijven', '寫下姓名和電話號碼'),
                             ('Doorgeven wanneer Evelien terug is', '轉告 Evelien 何時回來'),
                             ('Doorverbinden met de directeur', '轉接給總監'),
                             ('Vragen waar het over gaat', '詢問是什麼事')],
                 'answer': 0,
                 'source': [('33:21', 'Dan schrijf je de naam op van de beller en zeg je dat Evelien terugbelt.',
                             '那你就寫下來電者的姓名，並說 Evelien 會回電。'),
                            ('33:27', 'Vergeet ook niet het telefoonnummer.',
                             '也別忘了電話號碼。')],
                 'explain': '替同事接電話：寫下「姓名 + 電話號碼」，告訴對方 Evelien 會回電。',
                 'trap': '「詢問是什麼事」是找總監時的規矩；轉接總監也是別件事。要對準「Evelien 午休」這個情境。'},
            ],
        },
        {
            'title_zh': '同學的語音留言（分組作業）', 'title_nl': 'Marcus spreekt een bericht in over de groepsopdracht',
            'kind': '語音留言', 'dialogue': (319, 326),
            'context_zh': 'Nika 在上荷蘭語課。同學 Marcus 在她的語音信箱留言，討論小組作業的分工和碰面時間。',
            'vocab': [
                {'nl': 'de groepsopdracht', 'zh': '小組作業'},
                {'nl': 'inleveren', 'zh': '繳交'},
                {'nl': 'samen doen', 'zh': '一起做'},
                {'nl': 'afspreken', 'zh': '約（時間／碰面）'},
                {'nl': 'het liefst', 'zh': '最好是、最希望'},
            ],
            'patterns': [
                {'nl': 'Die moeten we ... inleveren', 'zh': '那個我們得在……交',
                 'note': 'moeten + 句尾動詞。'},
                {'nl': 'Zullen we ... of ... afspreken?', 'zh': '我們約……還是……？',
                 'note': '提議二選一。'},
            ],
            'questions': [
                {'n': 15, 't': '35:00',
                 'q_nl': 'Welke vraag moeten Nika en Marcus samen maken?',
                 'q_zh': '哪一題是 Nika 和 Marcus 要一起做的？',
                 'options': [('Vraag 1', '第 1 題'), ('Vraag 2', '第 2 題'),
                             ('Vraag 3', '第 3 題'), ('Vraag 4', '第 4 題')],
                 'answer': 1,
                 'source': [('34:44', 'Dan vraag 2, die zouden we samen doen.',
                             '那第 2 題，我們本來說要一起做。')],
                 'explain': 'Marcus 說「vraag 2 ... samen doen」——第 2 題一起做。',
                 'trap': '第 1 題 Marcus 已經做了；第 3、4 題是 Nika 在家做。四題都被點到名，要聽「samen」對到哪一題。'},
                {'n': 16, 't': '36:15',
                 'q_nl': 'Welke dag wil Marcus afspreken?',
                 'q_zh': 'Marcus 想約哪一天碰面？',
                 'options': [('Op maandag', '星期一'), ('Op dinsdag', '星期二'),
                             ('Op vrijdag', '星期五'), ('Op zaterdag', '星期六')],
                 'answer': 3,
                 'source': [('34:44', 'Zullen we vrijdag of zaterdag afspreken?',
                             '我們約星期五還是星期六？'),
                            ('34:48', 'Ja, het liefst zaterdag.', '嗯，最好是星期六。')],
                 'explain': 'Marcus 提議週五或週六，並說「het liefst zaterdag（最好是週六）」。',
                 'trap': '星期一是作業繳交死線；星期二是 Marcus 做第 1 題的日子。週五是被提到、但不是首選。'},
            ],
        },
        {
            'title_zh': '機場新聞（史基浦最忙的一天）', 'title_nl': 'Zaira kijkt naar het journaal over Schiphol',
            'kind': '新聞', 'dialogue': (358, 367),
            'context_zh': 'Zaira 在看電視新聞：昨天是史基浦機場今年最忙的一天。',
            'vocab': [
                {'nl': 'de drukste dag', 'zh': '最忙碌的一天'},
                {'nl': 'de passagier / de reiziger', 'zh': '旅客'},
                {'nl': 'inchecken', 'zh': '辦理報到'},
                {'nl': 'de paspoortcontrole', 'zh': '護照查驗'},
                {'nl': 'trakteren', 'zh': '請客、招待'},
            ],
            'patterns': [
                {'nl': '... was niet langer dan normaal', 'zh': '……並沒有比平常久',
                 'note': 'niet langer dan = 沒有比……更久——否定陷阱句。'},
                {'nl': 'Alleen ... was het lastig', 'zh': '只有在……比較麻煩',
                 'note': 'alleen 把唯一的例外標出來。'},
            ],
            'questions': [
                {'n': 17, 't': '~37:39', 'reconstructed': True,
                 'q_nl': 'Wat was bijzonder aan deze dag op Schiphol?',
                 'q_zh': '史基浦這一天有什麼特別之處？',
                 'options': [('Het was de drukste dag van deze zomer', '是今年夏天最忙的一天'),
                             ('Het was de drukste dag van het hele jaar', '是今年一整年最忙的一天'),
                             ('Het was de drukste dag van de afgelopen twee jaar', '是近兩年最忙的一天'),
                             ('Het was de drukste dag ooit', '是史上最忙的一天')],
                 'answer': 1,
                 'source': [('36:50', 'Gisteren was het de drukste dag van het jaar op Schiphol Airport.',
                             '昨天是史基浦機場今年最忙的一天。')],
                 'explain': '新聞開頭就說「de drukste dag van het jaar（今年最忙的一天）」。',
                 'trap': '去年夏天那天有 180,000 人，比昨天的 170,000 多——所以不是「史上」或「近兩年」最忙。數字是用來排除選項的。'},
                {'n': 18, 't': '39:05',
                 'q_nl': 'Waar hadden reizigers het meest last van de drukte?',
                 'q_zh': '旅客在哪裡最受人潮所苦？',
                 'options': [('In de rij voor het inchecken', '報到的排隊隊伍'),
                             ('Bij de paspoortcontrole', '護照查驗處'),
                             ('Op de parkeerplaats', '停車場')],
                 'answer': 2,
                 'source': [('38:40', 'Daarom waren de rijen voor het inchecken niet langer dan normaal.',
                             '所以報到的隊伍並沒有比平常長。'),
                            ('38:44', 'Ook de rij bij de paspoortcontrole was niet langer. Alleen op de parkeerplaats was het lastig om een plek te vinden.',
                             '護照查驗的隊伍也沒比較長。只有在停車場很難找到車位。')],
                 'explain': '報到、護照查驗都「niet langer（沒比較長）」，唯獨「Alleen op de parkeerplaats（只有停車場）」很麻煩。',
                 'trap': '報到和護照查驗都被 niet 否定掉了。聽到地點別急著選，要聽那句是肯定還是否定。'},
                {'n': 19, 't': '~40:30', 'reconstructed': True,
                 'q_nl': 'Waarom kregen reizigers op Schiphol gratis ijs?',
                 'q_zh': '史基浦的旅客為什麼拿到免費冰淇淋？',
                 'options': [('Omdat ze zo lang moesten wachten', '因為他們等了很久'),
                             ('Omdat Ola 20 jaar bestond', '因為 Ola 品牌成立滿 20 年'),
                             ('Omdat het zo’n warme dag was', '因為那天很熱')],
                 'answer': 1,
                 'source': [('40:15', 'Alle reizigers kregen gisteren wel gratis ijs van de ijsfabrikant.',
                             '昨天所有旅客都拿到了冰淇淋廠商送的免費冰淇淋。'),
                            ('40:19', 'Ola bestond 20 jaar en trakteerde.',
                             'Ola 品牌成立滿 20 年，所以請大家吃。')],
                 'explain': '發冰淇淋的原因是「Ola bestond 20 jaar（Ola 成立滿 20 年）」而請客。',
                 'trap': '「天氣熱」是情境（op zo’n warme dag），不是原因；等很久是停車場的事，跟冰淇淋無關。'},
            ],
        },
    ],
}


def build(meta: dict):
    d = json.loads((OUT / meta['video_id'] / 'data.json').read_text(encoding='utf-8'))
    segs = d['ai_data']['segments']
    info = d.get('video_info', {})
    scenarios = []
    for i, sc in enumerate(meta['scenarios'], 1):
        a, b = sc['dialogue']
        dlg = pull_dialogue(segs, a, b)
        qs = []
        for q in sc.get('questions', []):
            qs.append({
                'n': q['n'], 't': q['t'],
                'reconstructed': q.get('reconstructed', False),
                'q_nl': q['q_nl'], 'q_zh': q['q_zh'],
                'options': [{'nl': o[0], 'zh': o[1]} for o in q['options']],
                'answer': q['answer'],
                'source': [{'t': s[0], 'nl': s[1], 'zh': s[2]} for s in q['source']],
                'explain': q['explain'],
                'trap': q.get('trap', ''),
            })
        scenarios.append({
            'n': i,
            'title_zh': sc['title_zh'], 'title_nl': sc['title_nl'],
            'kind': sc['kind'], 'context_zh': sc['context_zh'],
            'start': dlg[0]['t'] if (dlg := dlg) else '',
            'no_questions': sc.get('no_questions', False),
            'dialogue': dlg,
            'vocab': sc['vocab'],
            'patterns': sc['patterns'],
            'questions': qs,
        })
    exam = {
        'video_id': meta['video_id'],
        'title': info.get('title', ''),
        'channel': info.get('channel', ''),
        'duration': info.get('duration', 0),
        'exam_type': meta['exam_type'],
        'intro': meta['intro'],
        'n_questions': sum(len(s['questions']) for s in scenarios),
        'scenarios': scenarios,
    }
    out = OUT / meta['video_id'] / 'exam.json'
    out.write_text(json.dumps(exam, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f"✓ {out.relative_to(ROOT)} — {len(scenarios)} scenarios, {exam['n_questions']} questions")
    return exam


if __name__ == '__main__':
    for m in (PART1, PART2):
        build(m)
